-- Create transactions table
CREATE TABLE IF NOT EXISTS `studious-union-470122-v7.finance.transactions` (
  transaction_id         STRING NOT NULL,
  user_id                STRING,
  account_id             STRING,
  document_id            STRING,
  parsing_run_id         STRING,
  transaction_date       DATE NOT NULL,
  posting_date           DATE,
  booking_datetime       DATETIME,
  amount                 NUMERIC NOT NULL,
  currency               STRING NOT NULL,
  balance_after          NUMERIC,
  direction              STRING,
  raw_description        STRING NOT NULL,
  normalized_description STRING,
  merchant_id            STRING,
  merchant_name          STRING,
  merchant_country       STRING,
  category_id            STRING,
  subcategory_id         STRING,
  category_name          STRING,
  subcategory_name       STRING,
  statement_line_no      INT64,
  statement_page_no      INT64,
  is_pending             BOOL,
  is_refund              BOOL,
  is_internal_transfer   BOOL,
  is_split_parent        BOOL,
  is_split_child         BOOL,
  external_reference     STRING,
  tags                   ARRAY<STRING> NOT NULL,
  created_ts             TIMESTAMP NOT NULL,
  updated_ts             TIMESTAMP,
  extra                  JSON
);
